language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/junegunn/vim-pseudocl.git
  git clone https://github.com/tpope/vim-repeat

  sudo apt-get remove -y vim vim-runtime vim-tiny vim-common
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge --prefix=/usr
  make VIMRUNTIMEDIR=/usr/share/vim/vim74
  sudo make install
  cd -

script: |
  /usr/bin/vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=vim-pseudocl
  set rtp+=vim-repeat
  set rtp+=.
  VIMRC) -c 'Vader! test/oblique.vader' > /dev/null
